package battleship.network;

public enum ConnectionEvent {
    UNKNOWN_COMMAND_RECEIVED,
    VERSION_COMMAND_RECEIVED,
    VERSION_COMMAND_SENT,
    VERSION_COMMAND_NOT_WELL_STRUCTURED,
    IAM_COMMAND_RECEIVED,
    IAM_COMMAND_SENT,
    IAM_COMMAND_NOT_WELL_STRUCTURED,
    IAMU_COMMAND_RECEIVED,
    IAMU_COMMAND_SENT,
    IAMU_COMMAND_INVALID,
    IAMU_COMMAND_NOT_WELL_STRUCTURED,
    COIN_COMMAND_RECEIVED,
    COIN_COMMAND_SENT,
    COIN_COMMAND_NOT_WELL_STRUCTURED,
    SHOOT_COMMAND_RECEIVED,
    SHOOT_COMMAND_SENT,
    SHOOT_COMMAND_NOT_WELL_STRUCTURED,
    HIT_COMMAND_RECEIVED,
    HIT_COMMAND_SENT,
    HIT_COMMAND_NOT_WELL_STRUCTURED,
    CHAT_COMMAND_RECEIVED,
    CHAT_COMMAND_SENT,
    CHAT_COMMAND_NOT_WELL_STRUCTURED,
    CHAT_COMMAND_INVALID,
    WITHDRAW_COMMAND_RECEIVED,
    WITHDRAW_COMMAND_SENT,
    WITHDRAW_COMMAND_NOT_WELL_STRUCTURED,

    NULL_LINE_RECEIVED,
    DISCONNECTED_WHILE_WAITING_FOR_COMMAND
}
